[package]
name = "ferrochain-exa-retriever"
version = "0.1.0"
edition = "2021"

[dependencies]
exa-sdk.workspace = true
ferrochain.workspace = true
http-client.workspace = true
serde_json.workspace = true
