[package]
name = "ferrochain-anthropic-completion"
version = "0.1.0"
edition = "2021"

[dependencies]
anthropic = { git = "https://github.com/fdionisi/anthropic-sdk", rev = "ca40d11cb516498b7b96fbce6f22384625c62f30" }
ferrochain.workspace = true
