[package]
name = "ferrochain-anthropic-completion"
version = "0.1.0"
edition = "2021"

[dependencies]
anthropic = { git = "https://github.com/fdionisi/anthropic-sdk", rev = "6126c4940aee86a218e4a75eefade511adc843de" }
ferrochain.workspace = true
