[package]
name = "ferrochain-qdrant-vectorstore"
version = "0.1.0"
edition = "2021"

[dependencies]
ferrochain.workspace = true
qdrant-client = "1.10.3"
serde_json.workspace = true
uuid = { version = "1.10.0", features = [
    "serde",
    "v4",
    "fast-rng",
    "macro-diagnostics",
] }
