[package]
name = "ferrochain-surrealdb-vectorstore"
version = "0.1.0"
edition = "2021"

[dependencies]
surrealdb.workspace = true
uuid.workspace = true
serde_json.workspace = true
ferrochain.workspace = true
